export class ErrorsUC {
    public static ERROR_USER_NOT_FOUND_BY_EMAIL = 'ERROR_USER_NOT_FOUND_BY_EMAIL'
    public static ERROR_USER_NOT_FOUND_BY_PHONE = 'ERROR_USER_NOT_FOUND_BY_PHONE'
    public static ERROR_SECRET_NOT_VALID = 'ERROR_SECRET_NOT_VALID'
    public static ERROR_AUTHCODE_NOT_FOUND = 'ERROR_AUTHCODE_NOT_FOUND'
    public static ERROR_AUTHCODE_NOT_VALID = 'ERROR_AUTHCODE_NOT_VALID'
    public static ERROR_AUTH_TYPE_NOT_VALID = 'ERROR_AUTH_TYPE_NOT_VALID'
    public static ERROR_BOTH_FIELDS_ARE_NOT_ALLOWED = 'ERROR_BOTH_FIELDS_ARE_NOT_ALLOWED'
    public static ERROR_AUTHCODE_NOT_FOUND_TO_RESEND = 'ERROR_AUTHCODE_NOT_FOUND_TO_RESEND'
}