export class ErrorsUC {
    public static ERROR_USER_NOT_FOUND_BY_EMAIL = 'ERROR_USER_NOT_FOUND_BY_EMAIL'
    public static ERROR_USER_NOT_FOUND_BY_PHONE = 'ERROR_USER_NOT_FOUND_BY_PHONE'
    public static ERROR_SECRET_NOT_VALID = 'ERROR_SECRET_NOT_VALID'
    public static ERROR_AUTHCODE_NOT_FOUND = 'ERROR_AUTHCODE_NOT_FOUND'
    public static ERROR_AUTHCODE_NOT_VALID = 'ERROR_AUTHCODE_NOT_VALID'
}